/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProcessState implements org.apache.thrift.TEnum {
  WAITING(0),
  FORKED(1),
  RUNNING(2),
  SUCCESS(3),
  KILLED(4),
  FAILED(5),
  LOST(6);

  private final int value;

  private ProcessState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProcessState findByValue(int value) { 
    switch (value) {
      case 0:
        return WAITING;
      case 1:
        return FORKED;
      case 2:
        return RUNNING;
      case 3:
        return SUCCESS;
      case 4:
        return KILLED;
      case 5:
        return FAILED;
      case 6:
        return LOST;
      default:
        return null;
    }
  }
}
