/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TaskState implements org.apache.thrift.TEnum {
  ACTIVE(0),
  CLEANING(5),
  FINALIZING(6),
  SUCCESS(1),
  FAILED(2),
  KILLED(3),
  LOST(4);

  private final int value;

  private TaskState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskState findByValue(int value) { 
    switch (value) {
      case 0:
        return ACTIVE;
      case 5:
        return CLEANING;
      case 6:
        return FINALIZING;
      case 1:
        return SUCCESS;
      case 2:
        return FAILED;
      case 3:
        return KILLED;
      case 4:
        return LOST;
      default:
        return null;
    }
  }
}
